substitutions:
  devicename: ehmtx

external_components:
   - source:
       type: local
       path: components

esphome:
  name: $devicename
  on_boot:
    lambda: |
       App.register_component(rgb328);

font:
  - file: monobit.ttf
    id: ehmtxfont
    size: 16
    glyphs:  |
      !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@<>

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: alarm
      variables:
        icon: int
        text: string
      then:
        lambda: |-
          id(rgb328)->add_alarm(icon,text);
    - service: screen
      variables:
        icon: int
        text: string
      then:
        lambda: |-
          id(rgb328)->add_screen(icon,text);
    - service: status
      variables:
        icon: int
      then:
        lambda: |-
          id(rgb328)->get_status(icon);
    - service: del_screen
      variables:
        icon: int
      then:
        lambda: |-
          id(rgb328)->del_screen(icon);

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EsphoMaTriX"
    password: "InM2TlqVfJe4"

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO04
    num_leds: 256
    rgb_order: GRB
    name: "$devicename Light"
    id: ehmtx_light
    default_transition_length: 1s
    color_correct: [30%, 30%, 30%]
    restore_mode: ALWAYS_OFF

time:
  - platform: homeassistant
    id: ehmtx_clock

display:
  - platform: addressable_light
    id: ehmtxdisplay
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb328)->tick();
      id(rgb328)->draw();
      
ehmtx:
  id: rgb328
  showclock: 6
  showscreen: 8
  display8x32: ehmtxdisplay
  time: 
  duration: 7
  font_id: ehmtxfont
  icons: 
    - file: sample.png
      id: boot 
    - file: sample.png
      id: temp 
    - file: sample.png
      id: garage